- NSOutlineViewAndTableView/NSOutlineViewAndTableViewExample/NSOutlineViewCode/NSOutlineViewExample.cs
- NSOutlineViewAndTableView/NSOutlineViewAndTableViewExample/NSTableViewCode/NSTableViewExample.cs
To enable scrolling in the NSOutlineViewAndTableView demo, the views need to be placed in NSScrollView and not NSClipView
> Place the views in an NSScrollView instead of NSClipView

- NSPortExample/MessageReceiver/MessageReceiver/AppDelegate.m
It was necessary to explicitly inform the type of the AppDelegate class in order to the "addItem:" method to be recognized by the compiler.
> Force type cast for AppDelegate

- HeartRateMonitor/HeartRateMonitor.cs
- HeartRateMonitor/HeartRateMonitorTableDataSource.cs
- HeartRateMonitor/MainWindow.designer.cs
- HeartRateMonitor/MainWindow.xib
- HeartRateMonitor/MainWindowController.cs
This is a general overhaul of the sample code with a few major highlights:
1. Refactor HeartRateMonitor such that it no longer directly derives from `CBPeripheralDelegate`; this ensures the public delegate API does not _bleed_ into HRM wrapper object API, yielding a cleaner public API. This also corrects a possible delegate disposal issue. Should fix: https://bugzilla.xamarin.com/show_bug.cgi?id=49285
2. Only create `HeartRateMonitor` objects when actually connecting to a peripheral, and ensure that only one instance of a peripheral is added to the peripheral list. Previously when any discovery event occurred, the same peripheral may have been added to the list multiple times, with each addition creating a new `HeartRateMonitor` for the peripheral again.
3. Add some console logging for …
> HeartRateMonitor: add features, fix bugs!

- ImageKitDemoStep1/ImageKitDemo.csproj
- QTRecorder/QTRecorder.csproj
- SkinnableApp/SkinnableApp.csproj
- StillMotion/StillMotion/StillMotion.csproj
Mac samples that use QT apis will fail to build with release config, since static registrar is not supported. Update samples to use dynamic registrar with release config to fix this issue.
> [QAXM]Fix bug 53084

- CoreAnimationBook/CustomizeAnimation/MyView.cs
Fixes issue with line width not animating in CustomizeAnimation sample. Issue was brought up in forums [1], for which bug report 60373 [2] was filed. 
[1] https://forums.xamarin.com/discussion/105564/animations-example-is-not-working#latest
[2] https://bugzilla.xamarin.com/show_bug.cgi?id=60373
> Fixes line width not animating issue. 

- UserNotificationExample/UserNotificationExample/MainWindow.cs
This was due to subscribing to those events in the same button touch handler that is used to send the notification,
resulting in multiple event subscriptions when the button is clicked multiple times. 
Setting up the event subscriptions in the Initialize method avoids this minor issue.
> DidDeliverNotification and DidActivateNotification fires repeatedly.

- OpenGLViewSample/OpenGLViewSample/AppDelegate.cs
[QAXM] fix bug https://bugzilla.xamarin.com/show_bug.cgi?id=57657
Fullscreen is depreciated so used .Accelerated.
> Fix OpenGLViewSample

- MacCopyPaste/MacCopyPaste/Classes/ImageDocument.cs
- MacCopyPaste/MacCopyPaste/Classes/ImageInfo.cs
[QAXM] fix bug https://bugzilla.xamarin.com/show_bug.cgi?id=45890
Fixed crash on copy button.
Steps to reproduce:
1. Launch app, select image.
2. Click copy button, this will update pasteboard.
3. Close application & relaunch it.
4. Click on paste button. This will paste earlier copied image.
5. Click on copy button. App was crashing here.
> Samplefix maccopypaste

- QTRecorder/QTRecorder.csproj
- QTRecorder/README.md
Added `MonoBundlingExtraArgs` to debug configuration and updated `Readme` file
> Fixed debug configuration for QTRecorder

- CoreWLANWirelessManager/CoreWLANWirelessManager/Info.plist
Fixes https://github.com/xamarin/mac-samples/issues/48
> Fix mac-samples bug #48 CoreWLANWirelessManager fails to build with Xamarin.Mac 4.3.0

- HeartRateMonitor/MainWindowController.cs
The sample in High Sierra is racy  when registering to the
CBCentralManager events. The scan method needs to be called once we are
sure that the manager is on and ready, else, events wont be correctly
dealt with.
Bugzilla: https://bugzilla.xamarin.com/show_bug.cgi?id=60696
> [HeartRateMonitor] Fix events race condition. Fixes #60696

- NSCustomView/NSCustomView/NSCustomView.csproj
It was unclear that we had the same name for folders, solution, project, namespace but not for the assembly and `.app`
> [XM] updated assembly name for the "NSCustomView" project

- MarkdownViewer/Markdown.csproj
- MarkdownViewer/MarkdownActions.targets
- added a`dylib` like a `NativeReference`
- added the same `CustomCommands` to the each `PropertyGroup` 
Before build the `dylib` added to the `Resources` folder and the project already linked with it.
Fixed: 
1. https://bugzilla.xamarin.com/show_bug.cgi?id=47052 (warning == `NativeReference`)
2. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/579738?src=alerts&src-action=cta (additional custom commands)
> [XM] fixed native ref linking and warning for the "Markdown" project

- MacCustomControl/MacCustomControl/CustomGraphics/CustomControlsStyleKit.cs
- MacCustomControl/MacCustomControl/UIKit/NSMutableParagraphStyle.cs
- MacCustomControl/MacCustomControl/UIKit/NSShadow.cs
- MacCustomControl/MacCustomControl/UIKit/UIBezierPath.cs
- MacCustomControl/MacCustomControl/UIKit/UIColor.cs
- MacCustomControl/MacCustomControl/UIKit/UIFont.cs
- MacCustomControl/MacCustomControl/UIKit/UIGraphics.cs
- MacCustomControl/MacCustomControl/UIKit/UIGraphicsContext.cs
- MacCustomControl/MacCustomControl/UIKit/UIImage.cs
- MacCustomControl/MacCustomControl/UIKit/UIStringDrawing.cs
- removed all `System.Drawing` usings because the app is not built successfully in Full mode
> [XM] removed `System.Drawing` usings; "MacCustomControl"

- CoreWLANWirelessManager/CoreWLANWirelessManager/MainWindow/MainWindowController.cs
Fixed a case when there is no interfaces. 
We run our tests on bots and some of them is VM. It [crashed](http://xqa.blob.core.windows.net/gist/report-66047010f4cf4c5ebcac93c6d264e4e6.txt) there because there is no network interfaces.
> Fixed 'CoreWLANWirelessManager' sample

- MacCopyPaste/MacCopyPaste/Classes/ImageInfo.cs
- Fixes https://github.com/xamarin/mac-samples/issues/93
- Fixes runtime error:
```shell
frame #12: 0x000000010bd16f93 MacCopyPaste`::xamarin_process_nsexception_using_mode(ns_exception=name: "NSInvalidUnarchiveOperationException" - reason: "This decoder will only decode classes that adopt NSSecureCoding. Class 'ImageInfo' does not adopt it.", throwManagedAsDefault=false) at runtime.m:2207
> INSCoding => INSSecureCoding to fix runtime error on paste.

- RoundedTransparentWindow/MainMenu.xib
The build was failed (xcode 10.1):
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(614,3): error : ibtool exited with code 1 [/Users/xamarinqa/agent/_work/r1/a/mac-samples/RoundedTransparentWindow/RoundedTransparentWindow.csproj]
MainMenu.xib : ibtool error : Compiling for earlier than macOS 10.6 is no longer supported. [/Users/xamarinqa/agent/_work/r1/a/mac-samples/RoundedTransparentWindow/RoundedTransparentWindow.csproj]
```
I've updated the `xib` file - just opened and re-saved it via Xcode 10
> Update `xib` file for 'RoundedTransparentWindow' sample

- MacWindows/MacWindows/MasterWindowController.cs
- MacWindows/MacWindows/ViewController.cs
Fix #123
Addresses one case of events + delegates colliding, in this case due to a newly added default delegate from Apple.
Detailed explanation here: xamarin/xamarin-macios#7569
I've validated that the sample builds + runs correctly with this fix :)
> Fix InvalidOperationException in MacWindows sample

- ButtonMadness/TestWindowController.cs
- MicroSamples/pdf/pdf.csproj
Fixes: https://github.com/xamarin/mac-samples/issues/132
ButtonMadness had a casing related typo in its `HfsTypeCode` enum usage.
MicroSamples/pdf does not contain any app icon or other Assets.xcassets
content, so the invalid `<ImageAsset/>` elements have been removed.
> Fix ButtonMadness and MicroSamples/pdf samples

- DragAndDropExample/DragAndDropExample/Classes/SourceView.cs
Set NSDraggingItem.DraggingFrame before starting dragging, otherwise the app
will crash:
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'NSDraggingItem.draggingFrame cannot be set to a zero size {{0, 0}, {0, 0}}'
*** First throw call stack:
(
0   CoreFoundation                      0x00007fff37b60b57 __exceptionPreprocess + 250
1   libobjc.A.dylib                     0x00007fff709ec5bf objc_exception_throw + 48
2   AppKit                              0x00007fff357cf275 -[NSDraggingItem draggingFrame] + 0
3   AppKit                              0x00007fff3562676e __61-[NSView(NSDrag) beginDraggingSessionWithItems:event:source:]_block_invoke + 175
4   CoreFoundation                      0x00007fff37ad8527 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
5 …
> [DragAndDropExample] Set NSDraggingItem.DraggingFrame before starting dragging. Fixes #135.

- CoreWLANWirelessManager/CoreWLANWirelessManager/AppDelegate.cs
As part of MacOS Catalina changes, it is now required to have location access to see BSSID data.
Fixes #129.
> [CoreWLANWirelessManager] Location Permission for BSSID Data. Fixes #129.
