- NSPortExample/MessageSender/MessageSender/MainWindowController.cs
This PR contains fix for NSPortExample  https://bugzilla.xamarin.com/show_bug.cgi?id=37192
> [NSPortExample] fix for # 37192

- MacOutlines/MacOutlines/ProductOutline/ProductOutlineDelegate.cs
[QAXM] fix bug https://bugzilla.xamarin.com/show_bug.cgi?id=45890
> [QAXM] fix bug https://bugzilla.xamarin.com/show_bug.cgi?id=45890

- QTRecorder/QTRecorder.csproj
- yosemite/Earthquakes/Earthquakes/Info.plist
Changed "Deployment Target" property to 10.10 from 10.8
> Fixed launch for Earthquakes 

- SCNetworkReachability/Info.plist
Added bundle identifier for SCNetworkReachability Mac sample.
> Fixed Bundle Identifier for SCNetworkReachability

- OutlineView/OutlineView/Info.plist
Added bundle identifier for OutlineView Mac sample.
> Fixed Bundle Identifier for OutlineView

- OpenGLViewSample/OpenGLViewSample/Info.plist
Added bundle identifier for openGLviewSample Mac sample.
> Fixed Bundle Identifier for OpenGLviewSample

- NSComboBoxTest/Info.plist
Added bundle identifier for NSComboBoxTest Mac sample.
> Fixed Bundle Identifier for NSComboBoxTest

- StillMotion/StillMotion/Info.plist
Added bundle identifier for StillMotion Mac sample.
> Fixed Bundle Identifier for StillMotion

- .gitignore
- CoreAnimationBook/CustomizeAnimation2/Info.plist
- NSComboBoxTest/Info.plist
I've updated the deployment target version for 2 applications and gitignore
> [XM] updated the deployment target version and gitignore

- CFNetwork/AsyncTests.Framework/AsyncTests.Framework.csproj
- CFNetwork/AsyncTests.Framework/packages.config
I missed that all projects should have this nuget. So I added it to the latest one which didn't have it before.
> [XM] fixed the "CFNetwork" sample

- CoreWLANWirelessManager/CoreWLANWirelessManager/MainWindow/MainWindowController.cs
@chamons  asked me to fix this issue (sometimes the `CountryCode ` property is null).
> [XM] fix CountryCode NRE

- SceneKitViewer/SceneView.cs
Fixes https://github.com/xamarin/mac-samples/issues/47
> Fix for path names with spaces

- GLSLShader/MyOpenGLView.cs
Here is the [issue](https://github.com/xamarin/xamarin-macios/issues/4417). 
I've fixed work of the application on VM - just by removing of hardware-acceleration.
> Fix NSOpenGLPixelFormat creation

- CFNetwork/MonoMac.CFNetwork.Test.csproj
It was System (Unsupported) and I switched it to the "Full Profile" target framework
> [CFNetwork] switched to "Full Profile"

- MarkdownViewer/Markdown.csproj
- MarkdownViewer/sundown/Makefile
Fixed:
```
MMP : error MM5109: Native linking failed with error code 1.  Check build log for details.
```
Related issue: 
https://github.com/xamarin/xamarin-macios/issues/4568
> [Markdown] updated a 'XamMacArch'

- HttpClient/HttpClient/ViewController.cs
> Fixed ' HttpClient' FullProfile mode

- yosemite/VisualEffectPlayground/VisualEffectPlayground/BasicSideViewController/BasicSidebarViewController.cs
- yosemite/VisualEffectPlayground/VisualEffectPlayground/DemoFaceTimeWindowController/DemoFaceTimeWindowController.cs
- yosemite/VisualEffectPlayground/VisualEffectPlayground/ImageLoader.cs
- yosemite/VisualEffectPlayground/VisualEffectPlayground/VibrantControlsViewController/VibrantControlsViewController.cs
Fixed #103 
These images are presented on Mojave and Hight Sierra.
> Fixed default images path [VisualEffectPlayground]

- SourceWriter/Documentation/html/class_app_kit_1_1_text_kit_1_1_formatter_1_1_source_text_view.html
- SourceWriter/Documentation/html/class_source_writer_1_1_template_view_controller.html
- SourceWriter/SourceWriter/Classes/AppPreferences.cs
- SourceWriter/SourceWriter/LanguageFormatter/SourceTextView.cs
- SourceWriter/SourceWriter/Main.storyboard
- SourceWriter/SourceWriter/TemplateViewController.cs
For docs update https://github.com/MicrosoftDocs/xamarin-docs/pull/1077
I replace the instances in the doxygen files rather than rebuilding though.
> typo: Langauge -> Language

- MacTables/MacTables/ProductTable/Product.cs
For docs update https://github.com/MicrosoftDocs/xamarin-docs/pull/1073
> typo: Propoperties -> Properties

- MacControls/MacControls/Main.storyboard
- MacControls/MacControls/SelectionViewController.cs
- MacControls/MacControls/SelectionViewController.designer.cs
To match docs update https://github.com/MicrosoftDocs/xamarin-docs/pull/1072
> typo: CollorWell -> ColorWell

- guiunit-example/Makefile
Fixes https://github.com/xamarin/mac-samples/issues/105.
> [guiunit-example] Update to build with msbuild and for x86_64. Fixes #105.

- VillainTracker/VillainTrackerAppDelegate.cs
- https://github.com/xamarin/mac-samples/issues/126
> Fix Villian Tracker exception
